version: 1
docker_image: mcr.microsoft.com/dotnet/sdk:8.0

setup_scripts:
  - name: restore
    run: dotnet restore ShiftPlanner.sln   # ルートなのでファイル名だけで可
  - name: build
    run: dotnet build ShiftPlanner.sln -c Release
  - name: test
    run: dotnet test  ShiftPlanner.sln --no-build
    