name: Build .NET Framework 4.8 WinForms App

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "**.md" ]  # optional: READMEなどの編集で無駄に走らせない
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # ← これが "Windowsランナー"

    steps:
    - name: ソースをチェックアウト
      uses: actions/checkout@v3

    - name: MSBuildをセットアップ
      uses: microsoft/setup-msbuild@v1.3.1

    - name: NuGetパッケージの復元
      run: nuget restore ShiftPlanner.sln

    - name: ビルドを実行
      run: msbuild ShiftPlanner.sln /p:Configuration=Release
